-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 17:55:56 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema expenses_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema expenses_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expenses_dev` DEFAULT CHARACTER SET utf8 ;
USE `expenses_dev` ;

-- -----------------------------------------------------
-- Table `expenses_dev`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `expenses_dev`.`users` ;

CREATE TABLE IF NOT EXISTS `expenses_dev`.`users` (
  `id` BIGINT(5) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(60) NULL,
  `created_at` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
